service: simple-motion-lighting-smartapp

package:
  patterns:
    - index.js
    - smartapp.js
    - locales/**

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x

functions:
  smartapp:
    handler: index.handle
    timeout: 20
