service: home-control

package:
  patterns:
    - index.js
    - smartapp.js
    - locales/**

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-west-2

functions:
  smartapp:
    handler: index.handle
    timeout: 20
