service: group-control

package:
  patterns:
    - index.js
    - smartapp.js
    - locales/**

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
          Resource: "arn:aws:dynamodb:us-west-2:674630936715:table/smartapp-context-store"
  
functions:
  smartapp:
    handler: index.handle
    timeout: 20
