service: sonos-control

package:
  patterns:
    - index.js
    - smartapp.js
    - locales/**

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  
functions:
  smartapp:
    handler: index.handle
    timeout: 20






service: oauth

app: helpful-oauth
tenant: alexbass

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless

functions:
  callback:
    handler: handler.callback
    events:
      - http:
          path: callback
          method: get
