service: oauth

app: sonos-oauth
# tenant: katesthings
package:
  patterns:
    - handler.js

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless

functions:
  callback:
    handler: handler.callback
    events:
      - http:
          path: callback
          method: get
