service: sonos-oauth

# app: sonos-oauth
# tenant: katesthings
package:
  patterns:
    - handler.js

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-west-2

functions:
  callback:
    handler: handler.callback
    events:
      - http:
          path: callback
          method: get
