service: sonos-oauth

package:
  patterns:
    - index.js
    - smartapp.js
    - locales/**
    - api/handler.js
    
provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-west-2

functions:
  smartapp:
    handler: index.handle
    timeout: 20
  callback:
    handler: handler.callback
    events:
      - http:
          path: callback
          method: get
